### ISSUE TITLE
Gateway stopped working after updating to 0.3.0

### ISSUE THREAD

**Issue by mathiasbl** [thomasddn/qbusmqtt#2]
See title.

Logs below.

cloudapp/QBUSMQTTGW/getConfig doesn't yield any devices. Any idea how I can make it work again?

<details>
<summary>log</summary>
[17:22:38] INFO: Retrieving MQTT settings from MQTT addon.
[17:22:40] INFO: Starting Qbus MQTT gateway.
[17:22:40] INFO: Connecting to MQTT broker 'core-mosquitto:1883' with user 'addons'.
I20240622 17:22:40.283015   121 MainApp.cpp:61] UbieLite (UbieLite, May 22 2024, 11:18:40)
I20240622 17:22:40.283291   121 MainApp.cpp:62] ==========================================
I20240622 17:22:40.283646   121 InterComm.cpp:142] (Main) createMailbox: Main, size: 5 Mbyte
I20240622 17:22:40.284000   121 InterComm.cpp:190] Mailbox: Main, is using a robuust mutex: true, Boost version: 1_58
I20240622 17:22:40.284345   121 IoServicePool.cpp:121] IoService pool 'RenRem' created with poolsize: 1
E20240622 17:22:40.293648   121 ConfigFileStorage.cpp:217] Unable to open file: '/opt/ubielite/fullconfig.json'
I20240622 17:22:40.294152   121 MainApp.cpp:96] Connecting via MQTT, host: tcp://core-mosquitto:1883, user: addons
I20240622 17:22:40.294808   121 IoServicePool.cpp:121] IoService pool 'Mqtt' created with poolsize: 1
I20240622 17:22:40.295054   121 MqttConnector.cpp:133] Using libmosquitto: 2.0.15
W20240622 17:22:40.295149   121 MqttCmdRouter.cpp:100] SSH User unknown, not creating SSH Tunnel manager
I20240622 17:22:40.295487   121 UriParser.cpp:65] mHost:core-mosquitto
I20240622 17:22:40.295570   121 MqttConnector.cpp:530] Connecting via Username/Pwd
I20240622 17:22:40.296065   121 MqttConnector.cpp:562] Connecting with server: core-mosquitto, port: 1883, keepaliveseconds: 60
I20240622 17:22:40.298767   131 Cli.cpp:198] Starting CLI on port: 5000
I20240622 17:22:40.298903   121 UbieSdk.cpp:89] Creating UbieSDK for: UbieLite
I20240622 17:22:40.298959   121 UbieSdk.cpp:90] Sdk Settings: AppName: UbieLite, InterComm: UbieLite, IdPrefix: UL, MainId: Main, LogicId: , Minimal Sdk: false
I20240622 17:22:40.299021   121 UbieSdk.cpp:106] No UbieSdkStorageIf provided, creating a local one
I20240622 17:22:40.299175   121 SdkPrivateConfig.cpp:28] Using private config file: /opt/ubielite/sdkconfig.json
E20240622 17:22:40.299336   121 Utilities.cpp:502] Unable to read file: /opt/ubielite/sdkconfig.json
W20240622 17:22:40.299393   121 SdkPrivateConfig.cpp:160] Private config file does not exists: /opt/ubielite/sdkconfig.json
I20240622 17:22:40.299978   121 InterComm.cpp:142] (UbieLite) createMailbox: UbieLite, size: 5 Mbyte
I20240622 17:22:40.300323   121 InterComm.cpp:190] Mailbox: UbieLite, is using a robuust mutex: true, Boost version: 1_58
I20240622 17:22:40.300420   121 InterComm.cpp:208] (UbieLite) registerMailbox: Main
I20240622 17:22:40.300572   121 UbieSdk.cpp:163] Watchdog nog enabled
E20240622 17:22:40.302171   121 AlarmSource.cpp:67] Translation file not found: /opt/ubielite/messages.json
I20240622 17:22:40.302469   121 DeviceManager.cpp:313] Reading device config from: /ubieroot/keys/device.json
E20240622 17:22:40.302680   121 DeviceManager.cpp:332] Unable to open file: '/ubieroot/keys/device.json'
E20240622 17:22:40.302829   121 FileStorage.cpp:502] Failed to open file: /opt/ubielite/qbushw.json
I20240622 17:22:40.302881   121 FileStorage.cpp:518] Config read, controllers found: 0
I20240622 17:22:40.304675   121 IoServicePool.cpp:121] IoService pool 'Main' created with poolsize: 4
I20240622 17:22:40.304766   124 StatusReceiver.cpp:291] StatusSender 'UbieLite' has registered, requesting all FB id's
I20240622 17:22:40.304883   124 InterComm.cpp:208] (Main) registerMailbox: UbieLite
I20240622 17:22:40.306550   121 IoServicePool.cpp:121] IoService pool 'Config' created with poolsize: 4
W20240622 17:22:40.307888   130 MqttConnector.cpp:388] MQTT Connected: success
I20240622 17:22:40.307934   121 IoServicePool.cpp:121] IoService pool 'LogPlayer' created with poolsize: 4
I20240622 17:22:40.308012   130 MqttRouter.cpp:162] MQTT broker connected
I20240622 17:22:40.308218   121 QbusMain.cpp:206] Using Sdk version: 1.0.5
I20240622 17:22:40.308277   121 UbieSdk.cpp:281] Register UbieSdkClient
I20240622 17:22:40.308315   121 ConfigClient.cpp:66] RequestConfig, sectionname: application.ubielite
I20240622 17:22:40.308669   124 ConfigManager.cpp:545] Storing config monitor for destination: UbieLite, sectionname: 'application.ubielite'
I20240622 17:22:40.308782   124 ConfigManager.cpp:891] Sendig configsection: 'application.ubielite', to destination: UbieLite
E20240622 17:22:40.308881   124 ConfigFileStorage.cpp:131] Section 'application' is not a valid section in the config
I20240622 17:22:40.358911   129 MqttRouter.cpp:1625] Sending Online to MQTT: {"id":"QBUSMQTTGW","online":true,"reason":"Connected @2024-06-22-17:22:40"}
I20240622 17:22:40.359117   129 MqttCmdRouter.cpp:272] Main connector is connected
I20240622 17:22:40.359164   129 ConfigManager.cpp:135] Cloud connected
I20240622 17:22:45.309813   136 FileStorage.cpp:534] Saving controller info to file: /opt/ubielite/qbushw.json
I20240622 17:22:45.320117   136 QbusMain.cpp:554] Creating controller, id: 1,  serial: 021614
I20240622 17:22:45.320369   124 ConfigManager.cpp:954] Store private config to file: /ubieroot/configbackup/UbieLite_2024-06-22-17-22.json
I20240622 17:22:45.330601   135 ActiveController.cpp:289] [UL1] Currently offline
E20240622 17:22:54.581326   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL31,  actual Id: UL31
E20240622 17:22:58.296085   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL31,  actual Id: UL31
E20240622 17:22:59.296304   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL31,  actual Id: UL31
E20240622 17:23:00.296357   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL31,  actual Id: UL31
W20240622 17:23:01.296321   128 StateFilter.cpp:290] Property UL31.value has timed out. age: 6715.4ms, resend count has been reached. Removing from queue
I20240622 17:25:54.724319   130 ConfigManager.cpp:228] ConfigManager: requestAllHcbConfigs
I20240622 17:25:54.724428   130 ConfigManager.cpp:231] Request a HCB Config from: UbieLite
E20240622 17:26:26.346377   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL4,  actual Id: UL4
E20240622 17:26:26.401342   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL5,  actual Id: UL5
E20240622 17:26:26.404534   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL3,  actual Id: UL3
E20240622 17:26:26.414175   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL8,  actual Id: UL8
E20240622 17:26:26.435467   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL6,  actual Id: UL6
E20240622 17:26:26.441011   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL7,  actual Id: UL7
E20240622 17:26:26.461433   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL2,  actual Id: UL2
E20240622 17:26:30.310177   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL2,  actual Id: UL2
E20240622 17:26:30.310307   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL6,  actual Id: UL6
E20240622 17:26:30.310353   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL8,  actual Id: UL8
E20240622 17:26:30.310391   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL3,  actual Id: UL3
E20240622 17:26:30.310427   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL7,  actual Id: UL7
E20240622 17:26:30.310467   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL5,  actual Id: UL5
E20240622 17:26:30.310529   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL4,  actual Id: UL4
E20240622 17:26:31.310784   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL2,  actual Id: UL2
E20240622 17:26:31.310909   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL6,  actual Id: UL6
E20240622 17:26:31.310954   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL8,  actual Id: UL8
E20240622 17:26:31.310993   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL3,  actual Id: UL3
E20240622 17:26:31.311031   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL7,  actual Id: UL7
E20240622 17:26:31.311069   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL5,  actual Id: UL5
E20240622 17:26:31.311108   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL4,  actual Id: UL4
E20240622 17:26:32.311316   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL2,  actual Id: UL2
E20240622 17:26:32.311419   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL6,  actual Id: UL6
E20240622 17:26:32.311458   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL8,  actual Id: UL8
E20240622 17:26:32.311496   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL3,  actual Id: UL3
E20240622 17:26:32.311532   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL7,  actual Id: UL7
E20240622 17:26:32.311576   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL5,  actual Id: UL5
E20240622 17:26:32.311618   134 FunctionBlockManager.cpp:761] Functionblock or Device not found. State id:  UL4,  actual Id: UL4
W20240622 17:26:33.311125   128 StateFilter.cpp:290] Property UL2.shutterPosition has timed out. age: 6850.2ms, resend count has been reached. Removing from queue
W20240622 17:26:33.311267   128 StateFilter.cpp:290] Property UL6.shutterPosition has timed out. age: 6876.26ms, resend count has been reached. Removing from queue
W20240622 17:26:33.311313   128 StateFilter.cpp:290] Property UL8.shutterPosition has timed out. age: 6897.73ms, resend count has been reached. Removing from queue
W20240622 17:26:33.311355   128 StateFilter.cpp:290] Property UL3.shutterPosition has timed out. age: 6907.42ms, resend count has been reached. Removing from queue
W20240622 17:26:33.311408   128 StateFilter.cpp:290] Property UL7.shutterPosition has timed out. age: 6870.95ms, resend count has been reached. Removing from queue
W20240622 17:26:33.311452   128 StateFilter.cpp:290] Property UL5.shutterPosition has timed out. age: 6910.76ms, resend count has been reached. Removing from queue
W20240622 17:26:33.311494   128 StateFilter.cpp:290] Property UL4.shutterPosition has timed out. age: 6965.81ms, resend count has been reached. Removing from queue
I20240622 17:26:54.642436   130 ConfigManager.cpp:228] ConfigManager: requestAllHcbConfigs
I20240622 17:26:54.642546   130 ConfigManager.cpp:231] Request a HCB Config from: UbieLite
</details>

**Comment by mathiasbl** [comment]
I restored a backup of 0.2.0. All working again. 

Based on the commits only the base image and configs paths changed though?

**Comment by thomasddn** [comment]
The binaries have also been changed. These are responsible for the communication between controller and mqtt.

I run v0.3 myself (as docker container, not as HA addon). How are you running this?

Can you try these steps:
- Shut down QbusMqtt and Qbha.
- Start Qbha.
- Start QbusMqtt and wait at least 5 minutes.

This should get it started. If not, you'll need to send a mqtt message manually. But let's try the above steps first.

Edit: if it's not working, please send the Qbha logs as well.

**Comment by mathiasbl** [comment]
Got it working with the steps you mentioned.

I have to look at the LQS value's tho. It seems the new binaries send different data... I can't figure out what this is based on. It doesn't match my daily or live usage.

![image](https://github.com/thomasddn/qbusmqtt/assets/16224711/75a33997-6e3c-418f-a967-df17d7c81301)

**Comment by mathiasbl** [comment]
And it stopped working.

I feel like the connection between the gateway and the controller just goes offline after a while.

**Comment by mathiasbl** [comment]
> Got it working with the steps you mentioned.
> 
> I have to look at the LQS value's tho. It seems the new binaries send different data... I can't figure out what this is based on. It doesn't match my daily or live usage.
> 
> ![image](https://private-user-images.githubusercontent.com/16224711/341985766-75a33997-6e3c-418f-a967-df17d7c81301.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzg0MjcsIm5iZiI6MTcxOTA3ODEyNywicGF0aCI6Ii8xNjIyNDcxMS8zNDE5ODU3NjYtNzVhMzM5OTctNmUzYy00MThmLWE5NjctZGYxN2Q3YzgxMzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE3NDIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZTRlZDY0NDI1YmY4OTIyZGVkYTFlMDQxZTgxMWUwMmZlZGMzMDIzM2MzZDdkNzc0NDBkNmE2ZGE5MzY2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k3Sbnv6KlpGGkHVqrqdZ7fcOD-jLbCBtiIdxmMxc07U)

Ok.... 
The new binaries doesn't add outputs for the LQS Dag, Nacht and Totaal.. The UL numbers got linked to the different ones. That's why we need 233 values for the Totaal. These are actually the 'Current' values of L1, L2, or L3.

I'll be sticking to the old binaries as it seems more stable (See timeout in the logs) and has the outputs I want/need.

**Comment by thomasddn** [comment]
It's hard to debug for me since I don't have a Luqas module. But I'll try to find out what is going on.

**Comment by mathiasbl** [comment]
I dont think theres much you can do. With the latest binaries the gauges are missing in the config json in mqtt.

**Comment by thomasddn** [comment]
I released a "new" version, which is just a rollback of the gateway binaries.
