### ISSUE TITLE
Qbus controller discovery: Invalid authentication found

### ISSUE THREAD

**Issue by ksmolder** [thomasddn/qbusmqtt#4]
I'm running qbusmqtt directly in docker. Qbusmqtt connects to the MQTT broker. However, it fails to create topics.

Setup:

- Qbus controller type: CDT01E
- Qbus controller version: 3.14
- Qbus ethernet firmware version: 6.0.9
- Custom password has been set for Qbus controller
- Docker network setup: not using the host driver in docker compose as the IoT network is on a separate VLAN. Instead using the macvlan network type to bridge the docker network with the actual vlan.

In the container, a file /opt/qbusmqttgw/qbushw.json is created with the following content:

```
# cat /opt/qbusmqttgw/qbushw.json
{"controllers":[{"auth":"","configFile":"","ctdVersion":"","ip":"192.168.2.11","lastConfig":"","mac":"XXXXXXXXXXXX","serialNr":"YYYYYY","version":"6.0.9"}],"idList":[{"YYYYYY":1}],"importDates":null,"peakPowers":null}
```

IP address, (redacted) MAC address and (redacted) serial number do correspond with the installed Qbus controller. So the basic discovery seems to work fine.

However, qbusmqtt cannot actually retrieve information. Every minute, an additional log entry is added to the qbusmqtt log file reading `22 Discovery.cpp:308] Invalid authentication found: ������������������������`. To me it seems I need "somehow" enter login credentials from the controller in qbusmqtt. But I cannot find any information on where (and how) to configure these credentials in qbusmqtt to connect to the controller.

**Comment by thomasddn** [comment]
I'm currently away from my computer. Will have a closer look when I'm back.

Could be due to authentication, never tested this tbh.

Have you also installed the QBHA container? The controller must be activated to work with mqtt, this is done by the QBHA container.

**Comment by ksmolder** [comment]
Thanks for the update and assistance!

Didn't install the QBHA container yet, as I wanted to focus on getting the data from the Qbus controller in the MQTT broker first. Will have a look at it probably tomorrow.

In the meantime I updated the `auth` section of the controller in  _qbushw.json_ by explicitly adding the value `<username>:<password>`. This resulted in the firmware  of the Eth controller being updated to version 6.1.3. So it appears to have some effect. However, I did keep seeing those `Invalid authentication found` errors in the log, so wasn't sure this actually solved something.

**Comment by ksmolder** [comment]
Just integrated the QBHA container in my setup and all seems to work now. Thanks for the hint and all the work you've put into this!

I'm not 100% confident I understand the impact of having a username/ password set on the Ethernet controller of the Qbus module. But wondering whether it's better to ask that question in https://github.com/Qbus-Koen/qbusMqtt as it's more related to the qbusMqttGw binary itself...

**Comment by thomasddn** [comment]
I would try to revert the changes you've made to `qbushw.json` and see if it still works. It shouldn't be touched manually and it could well be that no authentication is necessary.

I will close this issue, but don't hesitate to comment if you have further questions.
